#!/bin/bash

echo "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" > /etc/cron.d/banip
echo "* * * * * root /usr/local/ispmgr/addon/banip.cron.php  >/dev/null 2>&1" >> /etc/cron.d/banip
echo  "* * * * * root find /usr/local/ispmgr/var/.plugin_banip/ -type f -name 'cache.*' -atime +7 -delete >/dev/null 2>&1" >> /etc/cron.d/banip
echo >> /etc/cron.d/banip
